### ISSUE TITLE
method getPixels in class BitmapUtils cannot be applied to given types;

### ISSUE THREAD

**Issue by nurainnadhirah06** [aksel/steganography-app#3]
hello, i try to run my own project where I used your coding for reference. However, I encounter error on this part. I don't know how to solve it. I hope you can help me. This is for my final year project. Below are the coding and the code with bold is where the error happen.thank you in advance.

package com.example.bemyeyes.async;

import android.graphics.Bitmap;
import android.net.Uri;

import com.example.bemyeyes.utils.BitmapUtils;
import com.example.bemyeyes.utils.FileUtils;
import com.example.bemyeyes.utils.SteganographyUtils;

public class EncodeTask extends SteganographyTask{
    public EncodeTask(AsyncResponse<SteganographyParams> delegate) {
        super(delegate);
    }

        @Override
        protected SteganographyParams execute(SteganographyParams steganographyParams) {

            Bitmap bitmap = BitmapUtils.decodeFile(steganographyParams.getFilePath());
            int w = bitmap.getWidth();
            int h = bitmap.getHeight();
            int numberOfPixels = w * h;

            byte[] data = steganographyParams.getMessage().getBytes();

            int requiredLength = data.length * 8 + 32;

            if (requiredLength > numberOfPixels) {
            throw new IllegalArgumentException("Message is too long to fit into pixels.");
            }

            int[] encodedPixels = SteganographyUtils.encode(
                **BitmapUtils.getPixels(bitmap, requiredLength),**
                    steganographyParams.getMessage()
            );

            BitmapUtils.setPixels(bitmap, encodedPixels);

            Uri resultUri = FileUtils.saveBitmap(bitmap);

            steganographyParams.setResultUri(resultUri);

            steganographyParams.setType(AsyncResponse.Type.ENCODE_SUCCESS);
            return steganographyParams;
        }
}

**Comment by aksel** [comment]
I haven't worked on this in quite a while, so I am a bit unsure, but here goes:

`getPixels` expects two parameters: An instance of Bitmap, and an int. Before you do anything, double check that such a method exists in `com.example.bemyeyes.utils.BitmapUtils`.

Note that there are two `getPixels` methods in `com.akseltorgard.steganography.utils.BitmapUtils`. Does `com.example.bemyeyes.utils.BitmapUtils` also have both?

Also, just out of curiosity, what does this have to do with Be My Eyes?

**Comment by nurainnadhirah06** [comment]
> I haven't worked on this in quite a while, so I am a bit unsure, but here goes:
> 
> `getPixels` expects two parameters: An instance of Bitmap, and an int. Before you do anything, double check that such a method exists in `com.example.bemyeyes.utils.BitmapUtils`.
> 
> Note that there are two `getPixels` methods in `com.akseltorgard.steganography.utils.BitmapUtils`. Does `com.example.bemyeyes.utils.BitmapUtils` also have both?
> 
> Also, just out of curiosity, what does this have to do with Be My Eyes?

Thank you so much and yeah after I checked my com.example.bemyeyes.utils.BitmapUtils, there is only one method of getPixels method. After I added another method, there is no error.

BeMyEyes is the name of my mobile application. My aim is to develop an app for the victims of domestic violence to record their daily log and send it to the NGO. image-based steganography will be used in order for them to send it to the NGO. the logs can help the victims gain justice for themselves as it can be a good proof. The victims can only encode the content, while the NGO will decode it once they want to proceed with legal action. the content of the log will be saved in the realtime database and not in the device. That is the reason behind the name of BeMyEyes as it can be the eyes of truth for the victims.

Btw, can I know where did you learn how to build this app? through the internet or is it one of your course in the university? if you have the source where i can use it for my reference, mind to share with me because I'm having a hard time to learn image-based steganography. thank you so much and i really appreciate your help.

**Comment by aksel** [comment]
> After I added another method, there is no error.

That's good to hear. Your project is a cool use case for steganography!

I don't exactly remember where I learned this. I think steganography came as an idea through glitch art. Some friends and I were playing around, manipulating bits in pixels, and getting cool images as results. At some point, we must have had the thought of hiding arbitrary data in the pixels themselves.

This app was developed as part of an exam project. We had a bunch of other stuff, in order to cover many different courses - Android being just one of them.

If I remember correctly, we got the term steganography from our teacher; we had incorrectly been calling this "encrypting" messages in images, but it is not encryption, it is encoding.

**Comment by nurainnadhirah06** [comment]
![image](https://user-images.githubusercontent.com/67289315/99400829-6b414a80-2922-11eb-8105-df1d1b9cc581.png)
  Can i know why there are 2 layout for activity_encode.xml?

**Comment by aksel** [comment]
One is for landscape, one for portrait.

**Comment by nurainnadhirah06** [comment]
What is the need of the landscape layout?

**Comment by aksel** [comment]
If you wish to be able to rotate the phone.

**Comment by nurainnadhirah06** [comment]
hi, can we communicate through other platform(like WhatsApp,email or discord) because I need to ask you a lot of question and I think it is hard to communicate here. it is understandable if you feel uncomfortable about it:)

**Comment by aksel** [comment]
I'm afraid not; I don't have a lot of free time these days, and can't help you out too much :sweat_smile: 

I wish you good luck in the exam :smile:

**Comment by nurainnadhirah06** [comment]
hi, can i know what are the purpose of async and utils. Why does it need to be in the separate module in the java?
![image](https://user-images.githubusercontent.com/67289315/101022731-bf982b80-35ac-11eb-803d-8e9858df1a8f.png)

**Comment by aksel** [comment]
Hey, sorry, I missed this message.

I don't really understand your question, can you clarify?
