### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by brunokim** [aksel/steganography-app#5]
This project is missing a license. I'd like very much to fork it, but I need to know how do you intend to share it.

**Comment by aksel** [comment]
That's a good question. I haven't touched this app in a looong time, before I knew what licensing entailed.

I don't know if I have used some library somewhere in here, which constrains what license I can use. Maybe I'm even violating some license, by not having the license visible in the app. Who knows? Certainly not me :sweat_smile: 

But I'll add MIT, and cross my fingers that this won't fuck me down the line lool

Feel free to do whatever you want with this. :smile:
